# Generated by Django 2.0.6 on 2018-06-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0003_auto_20180618_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
